# Generated by Django 6.0.6 on 2026-06-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_workputplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='workputplan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workputplan',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
